steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "jobs",
        "update",
        "db",
        "--image",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_DB}:${_TAG}",
        "--region",
        "${_LOCATION}",
        "--wait",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "api",
        "--image",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_API}:${_TAG}",
        "--region",
        "${_LOCATION}",
        "--platform",
        "managed",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "services",
        "update-traffic",
        "api",
        "--to-latest",
        "--region",
        "${_LOCATION}",
      ]
