export const QUALIFIED = {
  answers: {
    referrer: "https://www.songbirdcare.com/",
    zip_code: "60634",
    sms_allowed: true,
    is_qualified: true,
    is_valid_zip: true,
    phone_number: "7738862010",
    email_address: "yyy@gmail.com",
    current_step_id: "10",
    "bracket_under_7?": true,
    is_qualified_age: true,
    parent_last_name: "M",
    "bracket_under_18?": true,
    child_age_bracket: "3_to_4",
    parent_first_name: "J",
    insurance_provider: "countycare",
    is_qualified_state: true,
    is_qualified_region: true,
    "bracket_10_and_under?": true,
    diagnostic_evaluation: "yes",
    is_qualified_insurance: false,
    is_parent_led_qualified: false,
    is_qualified_without_diagnosis: false,
  },
  finalized: true,
  created_at: "2023-01-26T17:17:00+00:00",
  flow_label: "test",
  variant_uuid: "c38748f7-2d27-4ac9-bef8-89faefa8f813",
  variant_label: "celebrate-final-eligibility",
  responder_uuid: "79cd6e69-ed72-4478-8352-2a0bb16eebad",
};

export const UNQUALIFIED = {
  answers: {
    referrer: "https://www.songbirdcare.com/",
    zip_code: "60634",
    sms_allowed: true,
    is_qualified: false,
    is_valid_zip: true,
    phone_number: "7738862010",
    email_address: "xxx@gmail.com",
    current_step_id: "10",
    "bracket_under_7?": true,
    is_qualified_age: true,
    parent_last_name: "xxx",
    "bracket_under_18?": true,
    child_age_bracket: "3_to_4",
    parent_first_name: "yyy",
    insurance_provider: "countycare",
    is_qualified_state: true,
    is_qualified_region: true,
    "bracket_10_and_under?": true,
    diagnostic_evaluation: "yes",
    is_qualified_insurance: false,
    is_parent_led_qualified: false,
    is_qualified_without_diagnosis: false,
  },
  finalized: true,
  created_at: "2023-01-26T17:17:00+00:00",
  flow_label: "test",
  variant_uuid: "c38748f7-2d27-4ac9-bef8-89faefa8f813",
  variant_label: "celebrate-final-eligibility",
  responder_uuid: "79cd6e69-ed72-4478-8352-2a0bb16eebad",
};
