# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Build and Deploy API"
        run: |
          cd "$GITHUB_WORKSPACE/typescript"
          make build-and-push-api

      - name: "Delete old images and revisions"
        continue-on-error: true
        run: |
          cd "$GITHUB_WORKSPACE/typescript"
          make delete-old-revisions
          make delete-old-images
